runtime: python311
service: default

# ⚠️ CRITICAL SECURITY WARNING ⚠️
# DO NOT put secrets here! This file is in Git!
# Use Google Secret Manager instead:
# https://cloud.google.com/secret-manager/docs/quickstart

env_variables:
  FLASK_ENV: production
  # Secrets moved to Google Secret Manager
  # Set them with: gcloud secrets create SECRET_NAME --data-file=-
  MONDAY_BOARD_ID: "2145240699"  # OK - not sensitive

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "glass-core-467907-e9:europe-west1:novahouse-chatbot-db"
