runtime: python311

# Konfiguracja dla Google App Engine
service: default

# Zmienne środowiskowe
env_variables:
  FLASK_ENV: production
  SECRET_KEY: "asdf#FGSgvasgf$5$WGT"

# Automatyczne skalowanie
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Zasoby instancji
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Obsługa plików statycznych
handlers:
- url: /static
  static_dir: src/static
  
- url: /.*
  script: auto

