runtime: python311

# Konfiguracja dla Google App Engine
service: default

# Zmienne środowiskowe + Cloud SQL
env_variables:
  FLASK_ENV: production
  SECRET_KEY: "asdf#FGSgvasgf$5$WGT"
  DATABASE_URL: "postgresql://chatbot_user:NovaH0use2025!DB@/chatbot?host=/cloudsql/glass-core-467907-e9:europe-west1:novahouse-chatbot-db"

# Automatyczne skalowanie
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Zasoby instancji
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Obsługa plików statycznych
handlers:
- url: /static
  static_dir: src/static
  
- url: /.*
  script: auto

# Cloud SQL Configuration
beta_settings:
  cloud_sql_instances: "glass-core-467907-e9:europe-west1:novahouse-chatbot-db"
