runtime: python311
service: default
instance_class: F4 # Upgraded from F2 - 2x więcej RAM i CPU

# ═══════════════════════════════════════════════════════════════
# PRODUCTION SECRETS - DO NOT COMMIT TO GIT!
# ═══════════════════════════════════════════════════════════════
#
# This file contains real production secrets.
# Keep it LOCAL ONLY - never commit to Git!
#
# To deploy:
# 1. Copy this file: cp app.yaml.secret app.yaml.prod
# 2. Deploy: gcloud app deploy app.yaml.prod
# 3. Delete local copy: rm app.yaml.prod
#
# ═══════════════════════════════════════════════════════════════

env_variables:
  FLASK_ENV: production

  # SECURITY: New credentials generated 2025-11-14
  SECRET_KEY: "2e2abf938bb057c9dea1515ec726a2ab4fc378399596e3309b1e310c4e3ff489"

  # Admin API Key (for backup, dashboard widgets, a/b testing)
  API_KEY: "V=iqRX16Zlp2TE+Hpz9pnT42it-L75SB"

  # Database - NEW PASSWORD (rotate PostgreSQL first!)
  DATABASE_URL: "postgresql://chatbot_user:vicNRNoO3TpLZzQ_BkAVbz886dW_J0Yo@/chatbot?host=/cloudsql/glass-core-467907-e9:europe-west1:novahouse-chatbot-db"

  # Monday.com
  MONDAY_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjU2MTI0OTM2MiwiYWFpIjoxMSwidWlkIjo2NzA0MDY5NCwiaWFkIjoiMjAyNS0wOS0xMlQwNjo1ODoxOC4yNzVaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6MjU4NDk4NzEsInJnbiI6ImV1YzEifQ.Z-5M7pm_QZa1YBQ4a5caSg6XZlM4X1_fTcnF5JmQJyw"
  MONDAY_BOARD_ID: "2145240699"

  # Redis (optional)
  # REDIS_URL: "redis://your-redis-host:6379/0"

  # Twilio SMS (optional)
  # TWILIO_ACCOUNT_SID: "ACxxxxx"
  # TWILIO_AUTH_TOKEN: "xxxxx"
  # TWILIO_PHONE_NUMBER: "+48XXXXXXXXX"

  # Google Cloud Storage (optional)
  # USE_CLOUD_STORAGE: "true"
  # GCS_BUCKET_NAME: "novahouse-uploads"

automatic_scaling:
  min_instances: 2 # Zmieniono z 1 - zawsze 2 instancje = zero cold starts
  max_instances: 15 # Zwiększono z 10
  target_cpu_utilization: 0.65
  min_idle_instances: 1 # Zawsze 1 instancja w gotowości
  max_idle_instances: 2

resources:
  cpu: 2 # Zwiększono z 1
  memory_gb: 1.0 # Zwiększono z 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "glass-core-467907-e9:europe-west1:novahouse-chatbot-db"
